[server]
port = 8080
host = "0.0.0.0"
base_url = "http://localhost:8080"

[admin]
password = "adminpassword"

[limits]
questions_per_hour = 6
questions_burst = 2

[ui]
site_name = "Anonymous Q&A"
description = "Ask me anything, anonymously!"
timeline = true
read_tracking = true

[ui.theme]
text = "#ffffff"
text_muted = "#9ca3af"
surface = "#2a2b2f"
background = "#1d1e22"
